[package]
name = "utils"
version = "0.29.2"
edition = "2021"
authors = ["Shuhui Luo <twitter.com/aureliano_law>"]
description = "Uniswap V3 SDK for Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/shuhuiluo/uniswap-v3-sdk-rs"
keywords = ["uniswap-v3", "ethereum", "sdk"]
exclude = [".github", ".gitignore", "rustfmt.toml"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
alloy-primitives = {version = "0.7.2", optional = false}
anyhow = "1.0"
aperture-lens = { version = "0.4", optional = true }
base64 = { version = "0.22", optional = true }
bigdecimal = "0.4.2"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-traits = "0.2.17"
once_cell = "1.19"
regex = { version = "1.10", optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = "1.0"
uniswap-sdk-core = "0.21.0"

[features]

[dev-dependencies]
